// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyhxhinjbqabtkfbzvkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aHhoaW5qYnFhYnRrZmJ6dmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Mzc3ODEsImV4cCI6MjA3NDIxMzc4MX0.-GQCxsD1dXRrxMxwxaSkwbqD-RIyO1AxdbJL_OJB3Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});